---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
  - name: bucc-ci
  - name: bucc

outputs:
  - name: bucc-state

params:
  VARS:
  ARGS: 

run:
  path: bucc-ci/ci/tasks/bucc-up/task
