---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bucc-ci
  - name: bucc

params: []

run:
  path: bucc-ci/ci/tasks/bucc-up-cpi-docker/task
