---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
  - name: bucc-ci
  - name: bucc-backup

outputs:
  - name: bucc-state-out

run:
  path: bucc-ci/ci/tasks/bucc-bbr-restore-creds/task
