---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: version
- name: bucc
- name: bucc-ci

outputs:
- name: release
- name: bucc-out

run:
  path: bucc-ci/ci/tasks/shipit/task
