---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: bucc
- name: bucc-ci
- name: bosh-release-concourse

outputs:
- name: bucc-out

run:
  path: bucc-ci/ci/tasks/update-concourse-release/task

params:
  OPS_FILE_PATH: ops/3-concourse-release.yml
  RELEASE_NAME: concourse
