---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
  - name: bucc-ci
  - name: bucc

outputs:
  - name: compile-manifest

params:
  RELEASES:

run:
  path: bucc-ci/ci/tasks/compile-manifest/task
