---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: bucc
- name: bucc-ci

outputs:
- name: bucc-generated-manifest

run:
  path: bucc-ci/ci/tasks/bucc-manifests/task

params:
  VARS:
