---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bucc-ci
  - name: bucc
  - name: compiled-releases-in

outputs:
  - name: compiled-releases-out

params: []

run:
  path: bucc-ci/ci/tasks/compile-releases/task
