---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bucc-ci
  - name: bucc
  - name: compiled-releases-concourse
  - name: compiled-releases-bosh-virtualbox-cpi
  - name: compiled-releases-bosh-aws-cpi
  - name: compiled-releases-bosh-azure-cpi
  - name: compiled-releases-bosh-docker-cpi
  - name: compiled-releases-bosh-google-cpi
  - name: compiled-releases-bosh-openstack-cpi
  - name: compiled-releases-bosh-vsphere-cpi

outputs:
  - name: compiled-releases

params: []

run:
  path: bucc-ci/ci/tasks/compile-releases/task
