---
meta:
  name: bucc
  target: sw
  url:     https://ci.starkandwayne.com
  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))
  vcenter:
    username: (( vault "secret/pipelines/bucc/vcenter:username" ))
    password: (( vault "secret/pipelines/bucc/vcenter:password" ))
  github:
    owner: starkandwayne
    repo:  bucc
    private_key:  (( vault "secret/pipelines/bucc/github:private" ))
    access_token: (( vault "secret/pipelines/bucc/github:token" ))
  aws:
    access_key_id: (( vault "secret/pipelines/bucc/aws:access_key_id" ))
    secret_access_key: (( vault "secret/pipelines/bucc/aws:secret_access_key_id" ))
  slack:
    webhook: (( vault "secret/pipelines/bucc/slack:webhook" ))
    channel: "#bucc"
