- type: replace
  path: /instance_groups/name=bosh/jobs/name=groundcrew/properties/additional_resource_types?
  value:
    - name: bosh-deployment
      type: docker-image
      source:
        repository: cloudfoundry/bosh-deployment-resource
        tag: v2.2.0
