- type: replace
  path: /releases/-
  value:
    name: prometheus
    version: 16.0.0
    url: https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=16.0.0
    sha1: 5cd0a326599c3c0ec7df406371b836cdebd37f00

- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value:
    name: bosh_tsdb_exporter
    release: prometheus
    properties:
      bosh_tsdb_exporter:
        metrics:
          namespace: ((director_name))
          environment: ((director_name))
        web:
          port: 9194
          auth_username: bosh_tsdb_exporter
          auth_password: &password ((bosh_tsdb_exporter_password))
          tls_cert: ((bosh_tsdb_exporter_tls.certificate))
          tls_key: ((bosh_tsdb_exporter_tls.private_key))

- type: replace
  path: /instance_groups/name=bosh/properties/hm/tsdb_enabled?
  value: true

- type: replace
  path: /instance_groups/name=bosh/properties/hm/tsdb?
  value:
    address: localhost
    port: 13321
  
- type: replace
  path: /variables/-
  value:
    name: bosh_tsdb_exporter_password
    type: password

- type: replace
  path: /variables/-
  value:
    name: bosh_tsdb_exporter_tls
    type: certificate
    options:
      ca: default_ca
      common_name: ((internal_ip))
      alternative_names: [((internal_ip))]
