---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
  - name: bucc-ci
  - name: bucc
  - name: update-cli

outputs:
- name: bucc-out

params:
  NAME:

run:
  path: bucc-ci/ci/tasks/update-cli/task
